import { registerCopy } from "@oneworld/shell";

/** Reviewed OneRide UI phrases for the four languages `W` does not carry inline. Keys are the
 *  English. Never pass member free text through here. */
const C: Record<string, readonly [string, string, string, string]> = {
  //                                   de                               ru                                     zh                     pt
  "Need a ride?": ["Brauchen Sie eine Fahrt?", "Нужна поездка?", "需要用车？", "Precisa de uma viagem?"],
  "Pick a driver, send your stops and time, and they reply with a price.": ["Wählen Sie einen Fahrer, senden Sie Stopps und Uhrzeit, und er antwortet mit einem Preis.", "Выберите водителя, отправьте остановки и время — он ответит ценой.", "选择司机，发送停靠点和时间，司机会给出报价。", "Escolha um motorista, envie as paradas e o horário, e ele responde com um preço."],
  "See drivers": ["Fahrer ansehen", "Смотреть водителей", "查看司机", "Ver motoristas"],
  "Drive with OneRide": ["Mit OneRide fahren", "Возить с OneRide", "加入 OneRide 当司机", "Dirija com o OneRide"],
  "Riders see your car's make, model and colour. Your plate stays private until a ride is accepted.": ["Fahrgäste sehen Marke, Modell und Farbe Ihres Autos. Ihr Kennzeichen bleibt privat, bis eine Fahrt angenommen ist.", "Пассажиры видят марку, модель и цвет автомобиля. Номер остаётся скрытым, пока поездка не принята.", "乘客能看到车辆的品牌、型号和颜色。车牌在行程被接受前保持私密。", "Os passageiros veem a marca, o modelo e a cor do carro. A placa fica privada até uma viagem ser aceita."],
  "Add my car": ["Mein Auto hinzufügen", "Добавить автомобиль", "添加我的车", "Adicionar meu carro"],
  "My car": ["Mein Auto", "Мой автомобиль", "我的车", "Meu carro"],
  "How a ride works": ["So funktioniert eine Fahrt", "Как проходит поездка", "行程如何进行", "Como funciona uma viagem"],
  "You ask a driver, with your stops and time.": ["Sie fragen einen Fahrer an, mit Stopps und Uhrzeit.", "Вы отправляете водителю остановки и время.", "您向司机发送停靠点和时间。", "Você pede a um motorista, com paradas e horário."],
  "The driver replies with a price.": ["Der Fahrer antwortet mit einem Preis.", "Водитель отвечает ценой.", "司机给出报价。", "O motorista responde com um preço."],
  "You accept it, and the ride is a contract.": ["Sie nehmen ihn an, und die Fahrt ist ein Vertrag.", "Вы принимаете её — и поездка становится договором.", "您接受报价，行程即成为合同。", "Você aceita e a viagem vira um contrato."],
  "You both press Start, and both press End.": ["Beide tippen auf Start und beide auf Ende.", "Оба нажимаете «Начать» и оба — «Завершить».", "双方都点“开始”，也都点“结束”。", "Os dois tocam em Iniciar e os dois em Encerrar."],
  "Drivers": ["Fahrer", "Водители", "司机", "Motoristas"],
  "No drivers yet.": ["Noch keine Fahrer.", "Пока нет водителей.", "还没有司机。", "Ainda não há motoristas."],
  "Verified": ["Verifiziert", "Проверен", "已验证", "Verificado"],
  "Request a ride": ["Fahrt anfragen", "Заказать поездку", "预约行程", "Pedir uma viagem"],
  "Requests open in the next update.": ["Anfragen werden mit dem nächsten Update freigeschaltet.", "Заказы откроются в следующем обновлении.", "预约将在下次更新中开放。", "Os pedidos abrem na próxima atualização."],
  "Choose a driver now. From here you will send them your pickup, stops and time.": ["Wählen Sie jetzt einen Fahrer. Von hier senden Sie Abholort, Stopps und Uhrzeit.", "Выберите водителя сейчас. Отсюда вы отправите место посадки, остановки и время.", "现在先选好司机。之后在这里发送上车点、停靠点和时间。", "Escolha um motorista agora. Daqui você vai enviar o embarque, as paradas e o horário."],
  "Year": ["Baujahr", "Год выпуска", "年份", "Ano"],
  "Make": ["Marke", "Марка", "品牌", "Marca"],
  "Model": ["Modell", "Модель", "型号", "Modelo"],
  "Colour": ["Farbe", "Цвет", "颜色", "Cor"],
  "Plate": ["Kennzeichen", "Госномер", "车牌", "Placa"],
  "Only you can see the plate. A rider sees it once you accept their ride.": ["Nur Sie sehen das Kennzeichen. Ein Fahrgast sieht es, sobald Sie seine Fahrt annehmen.", "Номер видите только вы. Пассажир увидит его, когда вы примете поездку.", "只有您能看到车牌。您接受行程后，乘客才能看到。", "Só você vê a placa. O passageiro a vê quando você aceita a viagem."],
  "Save car": ["Auto speichern", "Сохранить", "保存车辆", "Salvar carro"],
  "Saving…": ["Wird gespeichert…", "Сохранение…", "正在保存…", "Salvando…"],
  "Saved": ["Gespeichert", "Сохранено", "已保存", "Salvo"],
  "Remove car": ["Auto entfernen", "Удалить автомобиль", "移除车辆", "Remover carro"],
  "Remove": ["Entfernen", "Удалить", "移除", "Remover"],
  "Keep": ["Behalten", "Оставить", "保留", "Manter"],
  "Riders will no longer see you as a driver.": ["Fahrgäste sehen Sie dann nicht mehr als Fahrer.", "Пассажиры больше не увидят вас как водителя.", "乘客将不再看到您是司机。", "Os passageiros deixarão de ver você como motorista."],
  "Not verified yet": ["Noch nicht verifiziert", "Ещё не проверен", "尚未验证", "Ainda não verificado"],
  "Enter a year between 1980 and next year.": ["Geben Sie ein Jahr zwischen 1980 und nächstem Jahr ein.", "Укажите год от 1980 до следующего года.", "请输入 1980 年至明年之间的年份。", "Digite um ano entre 1980 e o próximo ano."],
  "Fill in every field.": ["Füllen Sie jedes Feld aus.", "Заполните все поля.", "请填写所有字段。", "Preencha todos os campos."],
  "Use 2 to 12 letters or numbers for the plate.": ["Das Kennzeichen hat 2 bis 12 Buchstaben oder Ziffern.", "Номер: от 2 до 12 букв или цифр.", "车牌需为 2 到 12 个字母或数字。", "A placa deve ter de 2 a 12 letras ou números."],
  "That did not save. Try again.": ["Das wurde nicht gespeichert. Bitte erneut versuchen.", "Не удалось сохранить. Попробуйте ещё раз.", "未能保存，请重试。", "Não foi salvo. Tente de novo."],
  "Rides": ["Fahrten", "Поездки", "行程", "Viagens"],
  "Request": ["Anfragen", "Заказать", "约车", "Pedir"],
  "Driver": ["Fahrer", "Водитель", "司机", "Motorista"],
  "Alerts": ["Hinweise", "Уведомления", "提醒", "Avisos"],
  "Nothing yet.": ["Noch nichts.", "Пока ничего.", "暂无内容。", "Nada ainda."],
  "Accept {0}": ["{0} annehmen", "Принять {0}", "接受 {0}", "Aceitar {0}"],
  "Accepted at {0}": ["Angenommen für {0}", "Принято за {0}", "已以 {0} 接受", "Aceito por {0}"],
  "Add a stop": ["Stopp hinzufügen", "Добавить остановку", "添加停靠点", "Adicionar parada"],
  "Add the drop-off.": ["Fügen Sie das Ziel hinzu.", "Укажите место высадки.", "请添加下车地点。", "Adicione o destino."],
  "Add the pickup.": ["Fügen Sie den Abholort hinzu.", "Укажите место посадки.", "请添加上车地点。", "Adicione o embarque."],
  "Agreed price: {0}": ["Vereinbarter Preis: {0}", "Согласованная цена: {0}", "约定价格：{0}", "Preço combinado: {0}"],
  "Another driver has this ride.": ["Ein anderer Fahrer hat diese Fahrt.", "Эту поездку взял другой водитель.", "另一位司机已接下此行程。", "Outro motorista ficou com esta viagem."],
  "Ask for prices": ["Preise anfragen", "Запросить цены", "询价", "Pedir preços"],
  "Asking for prices": ["Preise werden angefragt", "Запрошены цены", "正在询价", "Pedindo preços"],
  "Bags, child seat, where to wait…": ["Gepäck, Kindersitz, wo warten…", "Багаж, детское кресло, где ждать…", "行李、儿童座椅、在哪里等…", "Malas, cadeirinha, onde esperar…"],
  "Booked": ["Gebucht", "Забронировано", "已预订", "Reservado"],
  "Booked at {0}": ["Gebucht für {0}", "Забронировано за {0}", "已以 {0} 预订", "Reservado por {0}"],
  "Cancel request": ["Anfrage stornieren", "Отменить заказ", "取消请求", "Cancelar pedido"],
  "Cancel ride": ["Fahrt stornieren", "Отменить поездку", "取消行程", "Cancelar viagem"],
  "Cancelled": ["Storniert", "Отменено", "已取消", "Cancelado"],
  "Change": ["Ändern", "Изменить", "更改", "Alterar"],
  "Choose at least one driver.": ["Wählen Sie mindestens einen Fahrer.", "Выберите хотя бы одного водителя.", "请至少选择一位司机。", "Escolha pelo menos um motorista."],
  "Choose drivers": ["Fahrer wählen", "Выбрать водителей", "选择司机", "Escolher motoristas"],
  "Date": ["Datum", "Дата", "日期", "Data"],
  "Decline": ["Ablehnen", "Отклонить", "拒绝", "Recusar"],
  "Declined": ["Abgelehnt", "Отклонил", "已拒绝", "Recusou"],
  "Drivers send their prices. You pick one.": ["Fahrer senden ihre Preise. Sie wählen einen.", "Водители присылают цены. Вы выбираете одну.", "司机发来报价，由您选择。", "Os motoristas enviam preços. Você escolhe um."],
  "Drop-off": ["Ziel", "Высадка", "下车地点", "Destino"],
  "Every driver you asked will be told.": ["Jeder angefragte Fahrer wird benachrichtigt.", "Все водители, которых вы попросили, получат уведомление.", "您询问过的每位司机都会收到通知。", "Cada motorista que você chamou será avisado."],
  "Fill in or remove the empty stop.": ["Füllen Sie den leeren Stopp aus oder entfernen Sie ihn.", "Заполните или удалите пустую остановку.", "请填写或删除空的停靠点。", "Preencha ou remova a parada vazia."],
  "Member": ["Mitglied", "Участник", "会员", "Membro"],
  "Messages": ["Nachrichten", "Сообщения", "消息", "Mensagens"],
  "My price": ["Mein Preis", "Моя цена", "我的价格", "Meu preço"],
  "My price: {0}": ["Mein Preis: {0}", "Моя цена: {0}", "我的价格：{0}", "Meu preço: {0}"],
  "Name your price.": ["Nennen Sie Ihren Preis.", "Назовите свою цену.", "请填写您的价格。", "Informe seu preço."],
  "New price": ["Neuer Preis", "Новая цена", "新价格", "Novo preço"],
  "New price: {0}": ["Neuer Preis: {0}", "Новая цена: {0}", "新价格：{0}", "Novo preço: {0}"],
  "No takers? Raise your price.": ["Niemand nimmt an? Erhöhen Sie Ihren Preis.", "Никто не берёт? Поднимите цену.", "没人接？提高您的价格。", "Ninguém aceitou? Aumente seu preço."],
  "Not chosen": ["Nicht gewählt", "Не выбран", "未被选中", "Não escolhido"],
  "Note for the driver": ["Hinweis für den Fahrer", "Комментарий для водителя", "给司机的备注", "Recado para o motorista"],
  "Open": ["Offen", "Открыт", "进行中", "Aberto"],
  "Or send your own price": ["Oder senden Sie Ihren eigenen Preis", "Или предложите свою цену", "或发送您自己的价格", "Ou envie seu próprio preço"],
  "Pick a time from now on.": ["Wählen Sie eine Zeit ab jetzt.", "Выберите время не раньше текущего.", "请选择现在之后的时间。", "Escolha um horário a partir de agora."],
  "Pick one or more drivers to ask.": ["Wählen Sie einen oder mehrere Fahrer.", "Выберите одного или нескольких водителей.", "选择一位或多位司机。", "Escolha um ou mais motoristas."],
  "Pickup": ["Abholort", "Посадка", "上车地点", "Embarque"],
  "Raise": ["Erhöhen", "Поднять", "提高", "Aumentar"],
  "Remove stop": ["Stopp entfernen", "Удалить остановку", "删除停靠点", "Remover parada"],
  "Request a ride · {0}": ["Fahrt anfragen · {0}", "Заказать поездку · {0}", "预约行程 · {0}", "Pedir uma viagem · {0}"],
  "Requested by {0}": ["Angefragt von {0}", "Заказчик: {0}", "由 {0} 发起", "Pedido por {0}"],
  "Requests for you": ["Anfragen an Sie", "Заказы для вас", "给您的请求", "Pedidos para você"],
  "Ride": ["Fahrt", "Поездка", "行程", "Viagem"],
  "Ride request": ["Fahrtanfrage", "Заказ поездки", "行程请求", "Pedido de viagem"],
  "Ride request cancelled": ["Fahrtanfrage storniert", "Заказ поездки отменён", "行程请求已取消", "Pedido de viagem cancelado"],
  "Rider's price: {0}": ["Preis des Fahrgasts: {0}", "Цена пассажира: {0}", "乘客出价：{0}", "Preço do passageiro: {0}"],
  "Search for an address": ["Adresse suchen", "Найти адрес", "搜索地址", "Buscar endereço"],
  "Send price": ["Preis senden", "Отправить цену", "发送价格", "Enviar preço"],
  "Send request": ["Anfrage senden", "Отправить заказ", "发送请求", "Enviar pedido"],
  "Send to {0} drivers": ["An {0} Fahrer senden", "Отправить {0} водителям", "发送给 {0} 位司机", "Enviar para {0} motoristas"],
  "Sending…": ["Wird gesendet…", "Отправка…", "正在发送…", "Enviando…"],
  "Sent a price": ["Hat einen Preis gesendet", "Прислал цену", "已报价", "Enviou um preço"],
  "Stop {0}": ["Stopp {0}", "Остановка {0}", "停靠点 {0}", "Parada {0}"],
  "That did not go through. Try again.": ["Das hat nicht geklappt. Bitte erneut versuchen.", "Не получилось. Попробуйте ещё раз.", "未能完成，请重试。", "Não deu certo. Tente de novo."],
  "That was not sent. Try again.": ["Das wurde nicht gesendet. Bitte erneut versuchen.", "Не отправлено. Попробуйте ещё раз.", "未发送，请重试。", "Não foi enviado. Tente de novo."],
  "The first driver to accept gets the ride. No takers? Raise it later.": ["Der erste Fahrer, der annimmt, bekommt die Fahrt. Niemand? Erhöhen Sie später.", "Поездку получит первый принявший водитель. Никто не взял? Поднимите цену позже.", "第一个接受的司机获得此行程。没人接？稍后再提高。", "O primeiro motorista que aceitar fica com a viagem. Ninguém? Aumente depois."],
  "The new price must be higher.": ["Der neue Preis muss höher sein.", "Новая цена должна быть выше.", "新价格必须更高。", "O novo preço precisa ser maior."],
  "The rider cancelled.": ["Der Fahrgast hat storniert.", "Пассажир отменил поездку.", "乘客已取消。", "O passageiro cancelou."],
  "This ride is no longer open.": ["Diese Fahrt ist nicht mehr offen.", "Эта поездка уже закрыта.", "此行程已不再开放。", "Esta viagem não está mais aberta."],
  "This ride is not available to you.": ["Diese Fahrt ist für Sie nicht verfügbar.", "Эта поездка вам недоступна.", "您无法查看此行程。", "Esta viagem não está disponível para você."],
  "This ride's time has passed.": ["Die Zeit dieser Fahrt ist vorbei.", "Время этой поездки прошло.", "此行程的时间已过。", "O horário desta viagem já passou."],
  "Time": ["Uhrzeit", "Время", "时间", "Hora"],
  "Waiting": ["Wartet", "Ожидание", "等待中", "Aguardando"],
  "Withdrawn": ["Zurückgezogen", "Отозван", "已撤回", "Retirado"],
  "You declined.": ["Sie haben abgelehnt.", "Вы отказались.", "您已拒绝。", "Você recusou."],
  "You have already answered.": ["Sie haben bereits geantwortet.", "Вы уже ответили.", "您已回复过。", "Você já respondeu."],
  "You have this ride.": ["Sie haben diese Fahrt.", "Эта поездка ваша.", "此行程归您。", "A viagem é sua."],
  "You sent {0}. Waiting for the rider.": ["Sie haben {0} gesendet. Warten auf den Fahrgast.", "Вы отправили {0}. Ждём пассажира.", "您已报价 {0}，等待乘客确认。", "Você enviou {0}. Aguardando o passageiro."],
  "Your driver": ["Ihr Fahrer", "Ваш водитель", "您的司机", "Seu motorista"],
  "Your price": ["Ihr Preis", "Ваша цена", "您的价格", "Seu preço"],
  "Your rides": ["Ihre Fahrten", "Ваши поездки", "您的行程", "Suas viagens"],
  "{0} stops": ["{0} Stopps", "Остановок: {0}", "{0} 个停靠点", "{0} paradas"],
};
const pick = (i: 0 | 1 | 2 | 3) => Object.fromEntries(Object.entries(C).map(([en, t]) => [en, t[i]]));
registerCopy({ de: pick(0), ru: pick(1), zh: pick(2), pt: pick(3) });
