/** de / pt / ru / zh for the shared "Where it is" block (overlay 48). English and Spanish are inline. */
import { registerCopy } from "@oneworld/shell";

registerCopy({
  de: {
    "The address was in {0}, so it was cleared. Enter an address in {1}.": "Die Adresse lag in {0} und wurde gelöscht. Geben Sie eine Adresse in {1} ein.",
    "The country changed to {0}, so the city and neighbourhood were cleared.": "Das Land wurde auf {0} geändert, daher wurden Stadt und Stadtteil gelöscht.",
    "The address is in {0}, not {1}.": "Die Adresse liegt in {0}, nicht in {1}.",
    "This address is in {0}, not {1}.": "Diese Adresse liegt in {0}, nicht in {1}.",
    "We can't find this address in {0}.": "Wir finden diese Adresse in {0} nicht.",
    "We can't find {0} in {1}.": "Wir finden {0} in {1} nicht.",
    "Use {0}": "{0} verwenden",
    "Keep as typed": "So lassen",
    "Undo": "Rückgängig",
    "Type it, or pick a suggestion": "Eingeben oder Vorschlag wählen",
    "Filled in from the address. Suggestions are cities in the country below.": "Wird aus der Adresse übernommen. Vorschläge sind Städte im Land darunter.",
    "Filled in from the address": "Wird aus der Adresse übernommen",
    "Check the address": "Prüfen Sie die Adresse",
  },
  pt: {
    "The address was in {0}, so it was cleared. Enter an address in {1}.": "O endereço era em {0}, por isso foi apagado. Informe um endereço em {1}.",
    "The country changed to {0}, so the city and neighbourhood were cleared.": "O país mudou para {0}, por isso a cidade e o bairro foram apagados.",
    "The address is in {0}, not {1}.": "O endereço fica em {0}, não em {1}.",
    "This address is in {0}, not {1}.": "Este endereço fica em {0}, não em {1}.",
    "We can't find this address in {0}.": "Não encontramos este endereço em {0}.",
    "We can't find {0} in {1}.": "Não encontramos {0} em {1}.",
    "Use {0}": "Usar {0}",
    "Keep as typed": "Manter como está",
    "Undo": "Desfazer",
    "Type it, or pick a suggestion": "Digite ou escolha uma sugestão",
    "Filled in from the address. Suggestions are cities in the country below.": "Preenchido pelo endereço. As sugestões são cidades do país abaixo.",
    "Filled in from the address": "Preenchido pelo endereço",
    "Check the address": "Verifique o endereço",
  },
  ru: {
    "The address was in {0}, so it was cleared. Enter an address in {1}.": "Адрес был в {0}, поэтому он удалён. Введите адрес в {1}.",
    "The country changed to {0}, so the city and neighbourhood were cleared.": "Страна изменена на {0}, поэтому город и район удалены.",
    "The address is in {0}, not {1}.": "Адрес находится в {0}, а не в {1}.",
    "This address is in {0}, not {1}.": "Этот адрес находится в {0}, а не в {1}.",
    "We can't find this address in {0}.": "Мы не нашли этот адрес в {0}.",
    "We can't find {0} in {1}.": "Мы не нашли {0} в {1}.",
    "Use {0}": "Выбрать {0}",
    "Keep as typed": "Оставить как есть",
    "Undo": "Отменить",
    "Type it, or pick a suggestion": "Введите или выберите вариант",
    "Filled in from the address. Suggestions are cities in the country below.": "Заполняется по адресу. Подсказки — города страны ниже.",
    "Filled in from the address": "Заполняется по адресу",
    "Check the address": "Проверьте адрес",
  },
  zh: {
    "The address was in {0}, so it was cleared. Enter an address in {1}.": "该地址位于{0}，已被清除。请输入{1}的地址。",
    "The country changed to {0}, so the city and neighbourhood were cleared.": "国家已改为{0}，城市和街区已清除。",
    "The address is in {0}, not {1}.": "该地址位于{0}，而不是{1}。",
    "This address is in {0}, not {1}.": "此地址位于{0}，而不是{1}。",
    "We can't find this address in {0}.": "在{0}找不到此地址。",
    "We can't find {0} in {1}.": "在{1}找不到{0}。",
    "Use {0}": "使用{0}",
    "Keep as typed": "保持原样",
    "Undo": "撤销",
    "Type it, or pick a suggestion": "输入或选择建议",
    "Filled in from the address. Suggestions are cities in the country below.": "根据地址自动填写。建议为下方国家的城市。",
    "Filled in from the address": "根据地址自动填写",
    "Check the address": "请检查地址",
  },
});
