import { useEffect, useState } from "react";
import { useLocation } from "react-router-dom";
import { supabase } from "../lib/supabase";
import { useOneId } from "../lib/oneId";
import SignIn from "./SignIn";
import Splash from "./Splash";
import ProductMarquee from "../components/ProductMarquee";
import { signUpHref } from "../lib/authReturn";
import { createAuthEpoch } from "../lib/authEpoch";

/**
 * THE SIGN-ON GATE — the one surface single sign-on actually lives on.
 * ============================================================================================
 * Every product in the ecosystem sits behind this. It is the reason the shell exists as a shared
 * package rather than five copies: single sign-on is not a feature inside an app, it is a
 * property of the thing wrapping every app. You cannot test it without one, and you cannot trust
 * it if each app has its own.
 *
 * Two of the four apps failed sign-on before this — OneEvent showed "Sign in" on a detail page
 * while Lee was signed in, and OneScore said "guest" after arriving from OneJob's drawer. Both
 * were the same class of bug: each app deciding for itself what "signed in" means.
 *
 * ── Why this got dramatically simpler on 3 August ───────────────────────────────────────────
 * Everything now serves from ONE origin (`app.oneworldlabs.ai/job`, `/event`, …) instead of five
 * subdomains. Same origin means the session is simply shared — no cookie tricks, no handoff, no
 * redirect dance between hosts. The hardest problem of the rebuild dissolved into "there is only
 * one place."
 *
 * The parent-domain cookie adapter is kept for now because the marketing subdomains still exist
 * as doorways, and because reverting it is a one-line change if it is ever unnecessary. It costs
 * nothing to leave correct.
 */

type Phase = "checking" | "out" | "in";

export default function AuthGate({
  children,
  /** Shown while signed out. Product-scoped words; the structure never varies. */
  headline,
  sub,
  pitch,
  /** So the splash's flag row can only offer languages the product actually carries. */
  /** The product's mark, shown above the splash headline. */
  wordmark,
  /**
   * Paths anyone may see WITHOUT signing in.
   *
   * This gate was unconditional in the first cut, and that quietly broke the business: every
   * public profile (`/p/:id`), every "hire me" link and every contract sent to a client hit a
   * sign-in wall. Those links are generated by `hireLink()` and `contractLink()`, which are
   * documented as being pasted OUTSIDE the app — the whole point is that a stranger can open
   * them.
   *
   * It also contradicted the decision already made: let people look first, and ask for the
   * account at the first action that genuinely needs one. That is the moment a sign-up form is
   * cheap, because they have already seen why it is worth it.
   */
  publicPaths = [],
}: {
  children: React.ReactNode;
  headline: string;
  sub: string;
  /** 2-3 sentences under the sign-in block. Optional — see config.splash.pitchKey. */
  pitch?: string;
  wordmark?: import("../config").AppConfig["wordmark"];
  publicPaths?: (string | RegExp)[];
}) {
  const [phase, setPhase] = useState<Phase>("checking");
  const [showSignIn, setShowSignIn] = useState(false);
  const { loading: idLoading } = useOneId();

  useEffect(() => {
    const authEpoch = createAuthEpoch();

    /* Fires on sign-in, sign-out, token refresh, AND on another tab changing the session.
       That last one is what makes "sign out of one, signed out of all" true rather than
       aspirational — with everything on one origin, every open product hears it immediately. */
    const { data: sub } = supabase.auth.onAuthStateChange((_e, session) => {
      const eventRevision = authEpoch.advance();
      if (!authEpoch.isCurrent(eventRevision)) return;
      setPhase(session ? "in" : "out");
      if (session) setShowSignIn(false);
    });

    /* Subscribe first. A newer auth event must beat a delayed startup snapshot. */
    const startupRevision = authEpoch.capture();
    supabase.auth.getSession().then(({ data }) => {
      if (!authEpoch.isCurrent(startupRevision)) return;
      setPhase(data.session ? "in" : "out");
    });

    return () => { authEpoch.stop(); sub.subscription.unsubscribe(); };
  }, []);

  /* `useLocation()` — NOT `window.location`. Nothing else in this component subscribes to the
     router, so reading `window.location.pathname` in the render body meant the value never
     changed on a client-side navigation: a signed-out visitor who landed on a public profile and
     then navigated in-app to a private screen kept rendering children, because `isPublic` never
     recomputed. RLS is the real boundary so nothing leaked, but the moment real screens replace
     the placeholders it becomes a visible one.

     AND IT MUST BE CALLED BEFORE THE PHASE RETURN. Max, 5 Aug 2026, from a real browser at
     `/join`: React reported a changed Hooks order — the first render returned at
     `phase === "checking"` BEFORE this hook, the next render reached it. A hook after a
     conditional return violates the Rules of Hooks on every phase change, in every product,
     on every gated route; the words on screen were right while the render was broken
     underneath, which is exactly the class of defect a text assertion cannot see. The hook
     now runs unconditionally; only the CHECK below stays where it was, so public-path
     matching and auth behaviour are byte-for-byte unchanged. */
  const location = useLocation();
  const path = location.pathname;

  /* Render nothing rather than a spinner while we work out who this is.
     A spinner that resolves in 80ms reads as a stutter; nothing reads as instant. But if the
     check is genuinely slow, showing the signed-out screen first and then snapping to the app
     is worse — so we wait, and we wait on BOTH the session and the entitlements. */
  if (phase === "checking" || (phase === "in" && idLoading)) return null;

  /* A public path renders straight through, signed in or not. */
  const isPublic = publicPaths.some(m => (typeof m === "string" ? path.startsWith(m) : m.test(path)));
  if (isPublic) return <>{children}</>;

  if (phase === "out") {
    /* The sign-in destination is THIS product, not a generic home. Someone who deep-linked into
       a job listing and had to sign in should land back on that listing, not at square one.
       `location.pathname` is deliberate — the whole point of one origin is that this is simply
       true, with no hostname to reason about. */
    /* Where to send them AFTER sign-in — THE SAME PLACE THEY SIGNED IN FROM.
       On a real path, back to exactly where they were: someone who deep-linked into a job listing
       and had to sign in should land on that listing, not at square one.

       On the bare origin, back to the bare origin, which renders Your World once there is a
       session. This line used to read `landingPath(null)`, which is OneJob — so signing in from
       the company's own front door dropped you inside one product.

       Lee, 4 Aug 2026: *"I can go to oneworldlabs.ai and click sign in and it signs me directly
       into OneJob. It should have sent me to Your World. The only time it should take me to my
       jobs app is if that's where I was signing in."*

       Exactly right, and it is the SAME defect as the `autoForward` one — a well-meant default
       that answers "which product?" on a screen where the honest answer is "none of them yet".
       You leave sign-in where you entered it. */
    const next = path === "/" ? "/yourworld" : path + location.search + location.hash;

    return showSignIn
      ? (
        <div className="mx-auto grid min-h-screen max-w-lg place-items-center px-5">
          <div className="w-full">
            <SignIn next={next} />
            <button onClick={() => setShowSignIn(false)}
              className="ow-tap mt-5 w-full text-center text-[13px] font-medium opacity-45">
              Back
            </button>
          </div>
        </div>
      )
      /* ── THE MARQUEE BELONGS ON EVERY SPLASH, NOT JUST ONE WORLD'S ──────────────────────
         Lee, 11 Aug 2026, with screenshots of OneJob's and OneEvent's sign-in screens: he circled
         the EMPTY BAND between "Create account" and the One ID small print — *"it really should
         say the One World app."*

         He is right, and the gap was deliberate in a way that turned out to be wrong. `Splash`
         reserves a flexible middle and the comment on it said "Empty on the eight product
         splashes", so every product's sign-in screen had a large blank stripe where One World's
         has the family marquee. Two costs: the layout reads as unfinished, and somebody arriving
         through a jobs advert is never told the other apps exist — on the one screen where they
         are stopped and looking.

         Same component, same list, same behaviour as One World's own splash. Nothing here is
         product-specific, which is exactly why it can live in the shell and be right everywhere. */
      : <Splash headline={headline} sub={sub} pitch={pitch} wordmark={wordmark}
                 below={<ProductMarquee />}
                 onSignIn={() => setShowSignIn(true)}
                 onJoin={() => { window.location.href = signUpHref(next); }} />;
  }

  return <>{children}</>;
}
